version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.FastAPI
    restart: always
    depends_on:
    - mysql
    ports:
    - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.React
    depends_on:
    - backend
    ports:
    - 80:80

  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=elo_calculator_db
    image: mysql:5.7
    platform: linux/x86_64
    ports:
    - 3306:3306
    volumes:
    - ~/elo_calculator_db:/var/lib/mysql
