FROM node:20 as builder

RUN npm install -g npm@9.8.0

WORKDIR /app

COPY frontend/ ./

RUN npm install

RUN npm run build

FROM nginx

COPY --from=builder /app/build /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
